
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nklyzlsraydlftzfjrod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbHl6bHNyYXlkbGZ0emZqcm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MDM1MjksImV4cCI6MjA1NjA3OTUyOX0.03qRpZORtByHV8WV69eDUj_uNPHiOxPOjuHHQySJToo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get current user
export const getCurrentUser = async () => {
  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    console.error("Error getting user:", error);
    return null;
  }
  return data.user;
};

// Helper to ensure owner_id is set on data operations
export const withOwnerId = async (data: Record<string, any>) => {
  const user = await getCurrentUser();
  if (!user) {
    throw new Error('User not authenticated');
  }
  
  return {
    ...data,
    owner_id: user.id
  };
};
